### PR TITLE
build with symfony 5

### PR DESCRIPTION
**Pull request by dbu**
blocked by https://github.com/symfony-cmf/Routing/pull/240

### CODE REVIEW

**Comment by acrobat** [comment]
I think these dependencies should be updated to this version constraint, the `phpcr-odm` should be ok I think as 1.5 supports sf5

```
"matthiasnoback/symfony-dependency-injection-test": "^4.1.0",
"matthiasnoback/symfony-config-test": "^4.1.0",
```

**Comment by dbu** [comment]
hm, that did not help. i wonder if it is some change with symfony-cmf/testing that we no longer automatically get a phpcr-implementation and have to require that ourselves?

**Comment by dbu** [comment]
baby steps. now there are further missing dependencies for symfony 4, and for symfony 5 we need to adjust to BC breaks in the noback tests. i have to focus on work now again, if someone has time to try to get it to build, that would be great. 

@alexander-schranz i would prefer to see this building correctly before i tag symfony-cmf/Routing. and from what i understand, you use the bundle as well, so you need this merged anyways before sulu can support symfony 5?

**Comment by acrobat** [comment]
@dbu I will try to jump in and make some progress!

**Comment by dbu** [comment]
wrapped up in #448 , thanks a lot!

**Comment by dbu** [comment]
or rather: we merged #448 to here, need to merge this now :)

**Pull request merged**
