### PR TITLE
Correct create index for ORM

### PR DESCRIPTION
**Pull request by FaritSlv**
| Q             | A
| ------------- | ---
| Branch?       | 2.5.1
| Bug fix?      | no
| New feature?  |no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 
| License       | MIT
| Doc PR        | 

[Old PR](https://github.com/symfony-cmf/routing-bundle/pull/467)

### CODE REVIEW

**Comment by FaritSlv** [comment]
Hi @dbu is anything required of me?

**Review by dbu — APPROVED** [review]
thanks. i was on holidays, thats why i did not get to look into it sooner.

**Comment by FaritSlv** [comment]
Hi @dbu , will you be releasing a new release?

**Comment by dbu** [comment]
oh sorry. i meant to do that but then got sidetracked. here you go: https://github.com/symfony-cmf/routing-bundle/releases/tag/2.5.1

**Comment by FaritSlv** [comment]
@dbu thanks. I need this release =)

**Pull request merged**
