### PR TITLE
Removed *.class parameters

### PR DESCRIPTION
**Pull request by WouterJ**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | -
| License       | MIT
| Doc PR        | -

### CODE REVIEW

**Comment by gonzalovilaseca** [comment]
Why were the class parameters removed? 
What would the best practice be to override the `ChainRouter` class? Extend the bundle and add the service definition with out custom class?

**Comment by dbu** [comment]
> Why were the class parameters removed?
> What would the best practice be to override the |ChainRouter| class?
> Extend the bundle and add the service definition with out custom class?

this pattern got deprecated. if we would rename a class parameter, it
would randomly no longer match but not give you any error. the best
practice is to do a compiler pass that loads the service definition and
changes the class - and adjusts the service definition if needed.

why are you using a custom chain router? if its a general use case,
maybe we can also improve the ChainRouter provided by this bundle.

**Comment by gonzalovilaseca** [comment]
I don't think it's a general use case: we have url prefixes such as `es`, `us`, `rw` for all our routes, so that all of them are regionalised (and that dictates prices, etc.), when we generate a route, we add this prefix to it.

**Comment by dbu** [comment]
yes, this sounds like a special solution.

note: this is usually done in the specific router, not ChainRouter.
DynamicRouter supports locale prefixes, and for the core symfony router,
bundles to translate the URLs usually can do this as well.

**Comment by gonzalovilaseca** [comment]
Thanks for the suggestion!
We tried that approach, but we couldn't regionalise some bundles, so we moved it here as we regionalise all routes from all bundles. A request listener removes the prefix, and then the request is parsed normally, then we add the prefix when generating any url.

**Comment by dbu** [comment]
okay, thanks for explaining the use case. not something we need to move to
cmf, but interesting solution.

Am 13.03.2017 5:42 nachm. schrieb "Gonzalo Vilaseca" <
notifications@github.com>:

**Pull request merged**
