### PR TITLE
fixes composer memory limit

### PR DESCRIPTION
**Pull request by killerwolf**
| Q             | A
| ------------- | ---
| Branch?       | "master" for new features / the branch of the current release for fixes
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by dbu** [comment]
thanks! it seems that we end up with a "too new" phpunit. we should probably rather change the tests to use the namespaced phpunit classes than pin phpunit to an old version... would you be up to do that as well?

**Comment by killerwolf** [comment]
Crap....symfony-cmf/testing latest relase is so old,

**Comment by killerwolf** [comment]
@dbu  tests of the current code isn't the problem (which rely on the new phpunit namespaced classes) but symfony-cmf/testing.

**Comment by dbu** [comment]
we explicitly request phpunit 6 in https://github.com/symfony-cmf/routing-bundle/blob/master/.travis.yml#L33 - so this looks like a "how could this ever have worked" case. can we require a newer version of the symfony-cmf/testing library?

**Comment by dbu** [comment]
i am fixing this in #443 now. thanks for the effort @killerwolf

**Pull request closed without merging**
