### PR TITLE
Fix for invalid Jackrabbit characters in URLs

### LINKED ISSUE #430: Jackrabbit error when the URL has a leading or trailing space
Howdy,

If the URL entered by the user has a leading or trailing space then Jackrabbit produces an error. An example URL that produces an error is `/could-be-anything%20` or `/%20could-be-anything`. Note that spaces in the middle of the URL are fine.

Then when the Jackrabbit Request object tries to parse what came back from the server via loadXml, it produces the following error:

`Warning: DOMDocument::loadXML(): AttValue: &quot; or ' expected in Entity, line: 1`

This is the same error message as #259 .

I'm not positive I am reporting the error to the correct package, but since this has the same error message as the previous one I am reporting it here. If it belongs somewhere else, please let me know.

I am going to work around this issue by creating a high priority Kernel listener that detects leading and trailing spaces and removes them.

Here is what the Jackrabbit server sends back in the Request object: 

```<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<nodeTypes>
    <nodeType hasOrderableChildNodes="true" isAbstract="false" isMixin="false" isQueryable="true" name="nt:unstructured">
        <supertypes>
            <supertype>nt:base</supertype>
        </supertypes>
        <childNodeDefinition autoCreated="false" declaringNodeType="nt:unstructured" defaultPrimaryType="nt:unstructured" mandatory="false" name="*" onParentVersion="VERSION" protected="false" sameNameSiblings="true">
            <requiredPrimaryTypes>
                <requiredPrimaryType>nt:base</requiredPrimaryType>
            </requiredPrimaryTypes>
        </childNodeDefinition>
        <propertyDefinition autoCreated="false" declaringNodeType="nt:unstructured" fullTextSearchable="true" mandatory="false" multiple="false" name="*" onParentVersion="COPY" protected="false" queryOrderable="true" requiredType="undefined">
            <valueConstraints />
            <availableQueryOperators>
                <availableQueryOperator>jcr.operator.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.not.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.greater.than</availableQueryOperator>
                <availableQueryOperator>jcr.operator.greater.than.or.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.less.than</availableQueryOperator>
                <availableQueryOperator>jcr.operator.less.than.or.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.like</availableQueryOperator>
            </availableQueryOperators>
        </propertyDefinition>
        <propertyDefinition autoCreated="false" declaringNodeType="nt:unstructured" fullTextSearchable="true" mandatory="false" multiple="true" name="*" onParentVersion="COPY" protected="false" queryOrderable="true" requiredType="undefined">
            <valueConstraints />
            <availableQueryOperators>
                <availableQueryOperator>jcr.operator.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.not.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.greater.than</availableQueryOperator>
                <availableQueryOperator>jcr.operator.greater.than.or.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.less.than</availableQueryOperator>
                <availableQueryOperator>jcr.operator.less.than.or.equal.to</availableQueryOperator>
                <availableQueryOperator>jcr.operator.like</availableQueryOperator>
            </availableQueryOperators>
        </propertyDefinition>
    </nodeType>
</nodeTypes>

### PR DESCRIPTION
**Pull request by UFTimmy**
| Q             | A
| ------------- | ---
| Branch?       | "master" 
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Fixed tickets | #430
| License       | MIT
| Doc PR        | none

Fixes #430

### CODE REVIEW

**Comment by UFTimmy** [comment]
I added a note to the changelog, under 2.2.0 since I am not sure what version you were targeting this for.

As far as the version constraining, sorry, but I am not understanding what you mean at all. I confess my phpunit experience is very limited and my travis experience zero.

I am happy to help if you give me a little guidance.

**Comment by dbu** [comment]
> As far as the version constraining, sorry, but I am not understanding what you mean at all. I confess my phpunit experience is very limited and my travis experience zero.

The red thing saying "continous-integration/travis-ci/pr" links to the phpunit output [here](https://travis-ci.org/symfony-cmf/routing-bundle/jobs/484054772) which has `PHP Fatal error:  Class 'PHPUnit\Framework\Constraint\Constraint' not found`. i assume that this comes from composer installing a too new version of phpunit, because it used to work a few months ago.

we use symfony/phpunit-bridge so the phpunit version is constrained with https://github.com/symfony-cmf/routing-bundle/blob/master/.travis.yml#L34 

my approach to fix this problem would be too search the web for the fatal error message and phpunit-bridge and try to figure out what version we should use, or if there is a different problem.

(but i totally see that this is all rather obscure and not the best entry point into things when you are not familiar with phpunit and travis-ci. so no worries, i will try to look into this in the next days.)

**Comment by dbu** [comment]
i fixed the tests (essentially by upgrading to phpunit 6 and then cleaned up a bunch of stuff that i encountered) in #433 - can you please rebase this on master?

**Comment by UFTimmy** [comment]
@dbu I think I rebased correctly -- unfortunately my git experience is very limited. Let me know if there's anything more I need to do.

Thanks for all your help.

**Comment by ElectricMaxxx** [comment]
Hi @UFTimmy i would say: no worries about the rebase, if that would be a problem for contribution. If you like to get some help or explaining word. Just ping me in chat later.

**Comment by UFTimmy** [comment]
So based on the comment above I thought this was all squared away, but I am guessing my rebase messed everything up, as the list of committed files is now empty.

What do I need to do to make this work?

**Comment by dbu** [comment]
dang. yeah that rebase did not work as you wanted, because there are now no changes in this branch and github automatically closed the pull request. do you still have your change somewhere? if so, the easiest will be to create a new merge request. otherwise, if you still have the repository, try `git reflog` and see if you can find the commit. copy the hash, go to master and create a new branch, then `git cherry-pick <hash>`.

**Pull request closed without merging**
