### PR TITLE
Extract FormTypes from Admin

### PR DESCRIPTION
**Pull request by fbourigault**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| BC breaks? | no |
| Deprecations? | no |
| Tests pass? | yes |
| Fixed tickets | N/A |
| License | MIT |
| Doc PR | N/A |

I just opened, yet, this PR to start talking about implementation.

### CODE REVIEW

**Comment by fbourigault** [comment]
@dbu @wouterj  I started to look deeper in the code and found that the `RouteRefferersExtension` use a `Sonata\CoreBundle\Form\Type\CollectionType`. What do you think about moving around this coupling between cmf and sonata, do all the rest of work and use something else in another PR?

**Comment by ElectricMaxxx** [comment]
There is still an extraction in Progress.

**Comment by wouterj** [comment]
> What could be done here to allow extracting FormType from RouteReferrersExtension?

As the main goal of the form types is to provide reusable form types, let's use `CollectionType` of the Symfony form component here. As sonata needs some different handling, we can not use the form type for sonata integration and just keep the current code.

**Comment by fbourigault** [comment]
I'm closing this as it's no longer a goal. See https://github.com/symfony-cmf/sonata-phpcr-admin-integration-bundle/issues/53 for explanation.

**Pull request closed without merging**
